---
title: "Download_Data"
date: "2024-03-12"
format: html
editor_options: 
  chunk_output_type: console
---

# 1 Clear workspacce and set default color

```{r reset, include=FALSE}
graphics.off()
rm(list=ls(all.names=TRUE))
options(digits = 3)
```

# 2 Import functions and packages

```{r}

packages = c("tidyverse", "jsonlite")
suppressMessages(sapply(packages, library, character.only = TRUE))

source("https://raw.githubusercontent.com/chenyu-psy/R-functions/main/get-JATOS-data.R")
source("https://raw.githubusercontent.com/chenyu-psy/R-functions/main/read-json-files.R")

```

# 3 Experiment 1

## 3.1 Download data from JATOS

```{r}

# This function downloads data from JATOS
# and returns a table involving information about where the data is stored locally.
Table_jatos_files_ExpDemo <- get_JATOS_data(
  token = "jap_KRbJz0dIaT2CrZ1YScvBDcMpC0ty6Ik16fab4", # The token is valid until the 12th of May
  studyId = 559, # the study ID of your group
  batchId = 474, # Batch session ID, please remember to distinguish between the test session and the experiment session
  dataPath = str_glue("./raw_data/Data_Exp1/") # Please remember to create 
)

# Save the table locally so that you can load the data whenever you want.
Table_jatos_files_ExpDemo %>% write_csv(
  file = "./raw_data/Data_path_Exp1.csv"
)

```

## 3.2 Read data from the local file

```{r}

# Load the table with the data file information.
Table_jatos_files <- read_csv("./raw_data/Data_path_Exp1.csv")

# Filter participants who did not complete the experiment
Table_jatos_files_filtered <- Table_jatos_files %>% 
  filter(studyState == "FINISHED" | resultID == 13672, size > 100)

# Read participants' data
Raw_Exp1 <- read_json_files(Table_jatos_files_filtered$file)

unique(Raw_Exp1$participant)

Data_response <- Raw_Exp1 %>% 
  filter(expPart == "experiment") %>% 
  select(participant, blockID, trialID, screenID, character, stepID, position, initial_item, final_item, npl_items, response, acc, rt) %>% 
  mutate(
    updPos = ifelse(initial_item == final_item, "no","yes"),
    response = as.character(response)) %>% 
  rename(answer = response, block = blockID, trial = trialID, condition = character)

Data_response %>% write_csv(
  file = "./data/Data_Exp1_Res.csv"
)

Data_survey <- Raw_Exp1 %>% 
  filter(screenID == "survey") %>% 
  select(participant,response) %>% 
  unnest_wider(response)

Data_survey %>% write_csv(
  file = "./data/Data_Exp1_Survey.csv"
)


```

# 4 Experiment 2

## 4.1 Download data from JATOS

```{r}

# This function downloads data from JATOS
# and returns a table involving information about where the data is stored locally.
Table_jatos_files_Exp2 <- get_JATOS_data(
  token = "jap_KRbJz0dIaT2CrZ1YScvBDcMpC0ty6Ik16fab4", # The token is valid until the 12th of May
  studyId = 576, # the study ID of your group
  batchId = 493, # Batch session ID, please remember to distinguish between the test session and the experiment session
  dataPath = str_glue("./raw_data/Data_Exp2/") # Please remember to create 
)

# Save the table locally so that you can load the data whenever you want.
Table_jatos_files_Exp2 %>% write_csv(
  file = "./raw_data/Data_path_Exp2.csv"
)

```

## 4.2 Read data from the local file

```{r}

# Load the table with the data file information.
Table_jatos_files <- read_csv("./raw_data/Data_path_Exp2.csv")

# Filter participants who did not complete the experiment
Table_jatos_files_filtered <- Table_jatos_files %>% 
  filter(studyState == "FINISHED")

# Read participants' data
Raw_Exp2 <- read_json_files(Table_jatos_files_filtered$file)

unique(Raw_Exp2$participant)

Data_response <- Raw_Exp2 %>% 
  filter(expPart == "experiment",screenID!="debrief") %>% 
  select(participant, blockID, trialID, screenID, character, stepID, position, initial_item, final_item, npl_items, response, acc, rt) %>% 
  mutate(
    updPos = ifelse(initial_item == final_item, "no","yes"),
    response = as.character(response),
    npl_items = str_replace_all(npl_items,",",";")) %>% 
  rename(answer = response, block = blockID, trial = trialID, condition = character)

Data_response %>% write_csv(
  file = "./data/Data_Exp2_Res.csv"
)

Data_survey <- Raw_Exp2 %>% 
  filter(screenID == "survey") %>% 
  select(participant,response) %>% 
  unnest_wider(response)

Data_survey %>% write_csv(
  file = "./data/Data_Exp2_Survey.csv"
)


```







